addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.9.16")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.15.0")
addSbtPlugin("com.vmunier"        % "sbt-web-scalajs"          % "1.3.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"      % "0.21.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-web-scalajs-bundler"  % "0.21.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.6")
