addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "0.15.0")
addSbtPlugin("com.typesafe.sbt"   % "sbt-native-packager"      % "1.7.5")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.10.0")
addSbtPlugin("com.vmunier"        % "sbt-web-scalajs"          % "1.2.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"      % "0.21.1")
addSbtPlugin("ch.epfl.scala"      % "sbt-web-scalajs-bundler"  % "0.21.1")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.4.6")
